name: wetrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # CHANGED: Using a valid and modern SDK constraint for Dart 3+
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.13.6
  permission_handler: ^11.4.0
  firebase_storage: ^11.0.0
  image_picker: ^0.8.7+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/